[package]
name = "wesl_docs_compiler"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
wesl_docs = { path = "../wesl_docs" }

wesl = { git = "https://github.com/jannik4/wesl-rs", rev = "49d5d80d134ca26a2eb58ec779f064cdab23d519" }
